import React from 'react';
import { createRoot } from 'react-dom/client';
import { CLIENT_PLATFORMS, SCAFFOLD_NOTICE } from '@conductor/domain';
import './style.css';
function App() {
  const [view, setView] = React.useState<'overview' | 'boundaries'>('overview');
  return <main><aside><div className="wordmark">conductor<span>01</span></div><p className="eyebrow">DEVELOPMENT WORKBENCH</p><nav aria-label="Workspace"><button aria-current={view==='overview'?'page':undefined} onClick={()=>setView('overview')}>Overview</button><button aria-current={view==='boundaries'?'page':undefined} onClick={()=>setView('boundaries')}>Architecture</button></nav><p className="local">LOCAL DEVELOPMENT · S0</p></aside><section><p className="eyebrow">A FOUNDATION FOR DURABLE WORK</p><h1>{view==='overview'?'Your work has a home.':'Clear boundaries. Durable work.'}</h1><p className="intro">One task model across your desktop and phone. Independent execution hosts will keep work alive beyond a window.</p><div className="notice" role="status">{SCAFFOLD_NOTICE}</div>{view==='overview'?<><div className="cards"><article><span>01 / CLIENTS</span><h2>Five platforms</h2><p>{CLIENT_PLATFORMS.join(' · ')}</p></article><article><span>02 / RUNTIME</span><h2>Host + supervisor</h2><p>Rust entry points and a versioned health contract.</p></article><article><span>03 / NEXT MILESTONE</span><h2>Durable launch</h2><p>Journal commands and reconcile process start before adding agent execution.</p></article></div><div className="empty"><h2>No tasks yet</h2><p>This scaffold does not connect to a live host. Task creation arrives after the execution gates pass.</p><button disabled>Create task · not available</button></div></>:<div className="cards"><article><span>INTERACTION</span><h2>Desktop + mobile</h2><p>Render state and submit authorized intent. Never own process lifetime.</p></article><article><span>COORDINATION</span><h2>Optional service</h2><p>Team identity, assignment, remote delivery and notifications.</p></article><article><span>EXECUTION</span><h2>One attempt owner</h2><p>Supervise processes, isolate work and record evidence.</p></article></div>}<footer>INDEPENDENT IMPLEMENTATION · SPECIFICATION DATED 28 SEP 2026</footer></section></main>;
}
const root = document.getElementById('root');
if (!root) throw new Error('Missing application root');
createRoot(root).render(<App/>);
